server:
  port: 9091

spring:
  application:
    name: consumerfee
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

topics:
  fee:
    storage:
      topic: "fee.storage.topic.v1"